%% Showing necessary information
function mainInfo()
    disp("-----Define the Input Arguments-----")
    disp("->If the resister has 4 colour bands")
    disp("params.bandNo = 4")
    disp("params.col1 = color of the 1st color band")
    disp("params.col2 = color of the 2nd color band")
    disp("params.colMul = color of the 3rd color band")
    disp("params.colTol = color of the 4th color band")
    disp("  ")
    disp("->If the resister has 5 colour bands")
    disp("params.bandNo = 5")
    disp("params.col1 = color of the 1st color band")
    disp("params.col2 = color of the 2nd color band")
    disp("params.col3 = color of the 3rd color band")
    disp("params.colMul = color of the 4th color band")
    disp("params.colTol = color of the 5th color band")
    disp("  ")
    disp("-----Call the Function-----")
    disp("resistorValue(params)")
    disp("  ")
    disp("-----valid colors for input arguments-----")
    disp("col1/col2/col3 : black, brown, red, orange, yellow, green, blue, violet, grey, white")
    disp("colMul : black, brown, red, orange, yellow, green, blue, gold, silver")
    disp("colTol : brown, red, gold, silver")
    disp("  ")
    disp("-----examples-----")
    disp("params.bandNo = 4;")
    disp("params.col1 = 'green';")
    disp("params.col2 = 'blue';")
    disp("params.colMul = 'red';")
    disp("params.colTol = 'gold';")
    disp("resistorValue(params)")
    disp("  ")
    disp("params.bandNo = 5;")
    disp("params.col1 = 'yellow';")
    disp("params.col2 = 'violet';")
    disp("params.col3 = 'black';")
    disp("params.colMul = 'red';")
    disp("params.colTol = 'brown';")
    disp("resistorValue(params)")
end